version: "3.9"
services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: ecompta_api
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ../backend/data:/usr/src/app/data
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: ecompta_web
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped